/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 1000 [PANEL_PATTERN_ID]
      ,[BARCODE]
      ,[MODEL_NO]
      ,[SERIAL_NO]
      ,[LAST_MODIFIED_TIME]
      ,[OPERATOR_ID]
FROM [PanaCIM].[dbo].[panel_details]
WHERE BARCODE = '100473A061822500'

/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 1000 [PANEL_PLACEMENT_ID]
      ,[REEL_ID]
      ,[NC_PLACEMENT_ID]
      ,[PATTERN_NO]
      ,[Z_NUM]
      ,[PU_NUM]
      ,[PART_NO]
      ,[CUSTOM_AREA1]
      ,[CUSTOM_AREA2]
      ,[CUSTOM_AREA3]
      ,[CUSTOM_AREA4]
      ,[REF_DESIGNATOR]
      ,[PATTERN_IDNUM]
      ,[PATTERN_BARCODE]
      ,[PATTERN_DESIGNATOR]
      ,[PREPICKUP_LOT]
      ,[PREPICKUP_STS]
      ,[NCADD]
      ,[NHADD]
      ,[NBLKSERIAL]
      ,[PLACEMENT_ORDER]
      ,[FEEDER_BC]
FROM [PanaCIM].[dbo].[panel_placement_details]

/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 1000 [SERIAL_NO]
      ,[PROD_MODEL_NO]
      ,[PANEL_ID]
      ,[PATTERN_ID]
      ,[BARCODE]
      ,[SETUP_ID]
      ,[TOP_BOTTOM]
      ,[TIMESTAMP]
      ,[IMPORT_FLAG]
FROM [PanaCIM].[dbo].[tracking_data]